# Generated by Django 5.1.7 on 2025-03-25 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="user",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentcontent",
            name="document",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
        migrations.AlterModelOptions(
            name="documentversion",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
            },
        ),
        migrations.RenameField(
            model_name="documentversion",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="clarity_suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="grammar_suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="improved_file",
            field=models.FileField(
                blank=True, null=True, upload_to="improved_documents/"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="improved_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="original_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="original_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="style_suggestions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Suggestion",
        ),
        migrations.DeleteModel(
            name="DocumentContent",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="content",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="version_number",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
