# Generated by Django 5.1.7 on 2025-03-26 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_document_user_remove_suggestion_document_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentversion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
            },
        ),
        migrations.RenameField(
            model_name="documentversion",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="documentversion",
            name="content",
            field=models.TextField(default="No content Provided"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="document_versions/"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="suggestions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="version_type",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("improved", "Improved"),
                    ("exported", "Exported"),
                ],
                default="original",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("original_file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="documentversion",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="core.document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("document", "version_type")},
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="clarity_suggestions",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="grammar_suggestions",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="improved_file",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="improved_text",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="original_file",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="original_text",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="status",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="style_suggestions",
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="user",
        ),
    ]
